### PR TITLE
Code that downloads the SNIRH data

### LINKED ISSUE #14: Error on CURL
"the underlying connection was closed could not establish secure channel for ssl/tls"

URL: https://snirh.pt/snirh/_dadosbase/site/paraCSV/dados_csv.php?sites=920685260&pars=1436794570,1520200094&tmin=01/10/1965&tmax=10/03/2022&formato=csv

### PR DESCRIPTION
**Pull request by danielm09**
This code allows to download the SNIRH data (temp. and precipitation).
It uses cURL to download the csv file from the URL and then perform a series of cleaning procedures in the obtained data.
In the end, it provides the cleaned data in a dataframe structure. However, it is necessary to define to where the csv will be downloaded (last line).

When is finished close #14

### CODE REVIEW

**Review by MarouAna — APPROVED** [review]
Seems working

**Review by JJ — APPROVED** [review]
It looks good. There are a couple of nits:
* #15 creates specific directories for these test scripts. So is it possible that you make the base branch for this that branch (you can do that by editing the PR) and move it to one of those directories? If not, we can always do it when merged.
* You can use curl directly from a library called pycurl https://pypi.org/project/pycurl/
* CSV is also a standard library in Python. You can probably use it directly; and you will not even need pandas (we will probably need it later anyway)
* Remember that the objective of #13 was to *download*, so we would need to save the file in the exact same format, without even processing it to CSV

**Review by Rosa-Rafe — COMMENTED** [review]
a question:
the fist column will be date, what about columns; do they have title?

**Comment by danielm09** [comment]
> with "final_result = [i for i in result_lines_split if len(i)==6]" how could we delete lines that do not represent actual data (eg. header and footer)?

This line of code checks if the length of the element in the array is equal to six, which is the length of a valid data entry on the csv. If the length is different than six, it means that the element is probably not a data entry, but some other text. In this case, the other text is either the header or the footer.

**Comment by danielm09** [comment]
> a question: the fist column will be date, what about columns; do they have title?

The other columns are the temperature and precipitation. I did not need to explicitly name them, because they already came with the right names when I downloaded the data with curl.

**Comment by JJ** [comment]
You can now base it back in main, since the branch has already been merged

**Pull request merged**
